# Generated by Django 4.0 on 2021-12-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0017_auto_20210915_1639'),
        ('reward', '0002_auto_20211028_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name': 'Догана', 'verbose_name_plural': 'Догани'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Заоохочення та нагороди', 'verbose_name_plural': 'Заоохочення та нагороди'},
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='staff',
        ),
        migrations.AddField(
            model_name='penalty',
            name='osoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='osoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
