# Generated by Django 4.0 on 2021-12-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0017_auto_20210915_1639'),
        ('order', '0009_alter_statusorder_name'),
        ('reward', '0003_alter_penalty_options_alter_reward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='osoba',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='osoba',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець'),
        ),
    ]
