# Generated by Django 4.0 on 2021-12-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_statusorder_name'),
        ('reward', '0007_alter_rewardocoba_options_penalty_date_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_ocoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reward.rewardocoba', verbose_name='Reward Ocoba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='type_penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.typepenalty', verbose_name='Type Penalty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_ocoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.rewardocoba', verbose_name='Reward Ocoba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='type_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.typereward', verbose_name='Type Reward'),
            preserve_default=False,
        ),
    ]
