# Generated by Django 4.0 on 2021-12-31 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_allcontract'),
        ('reward', '0008_alter_penalty_order_alter_penalty_penalty_ocoba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='date_cancel',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date Cansel'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_ocoba',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reward.rewardocoba', verbose_name='Penalty Ocoba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='type_penalty',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='reward.typepenalty', verbose_name='Type Penalty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_ocoba',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='reward.rewardocoba', verbose_name='Reward Ocoba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='type_reward',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='reward.typereward', verbose_name='Type Reward'),
            preserve_default=False,
        ),
    ]
