# Generated by Django 3.2.10 on 2022-01-05 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0017_auto_20210915_1639'),
        ('reward', '0009_alter_penalty_date_cancel_alter_penalty_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(default=django.utils.timezone.now, verbose_name='Interview date')),
                ('topic', models.CharField(blank=True, max_length=512, verbose_name='Interview topic')),
                ('opinion', models.CharField(blank=True, max_length=512, verbose_name='Interview opinion')),
                ('osoba', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interview',
            },
        ),
    ]
