# Generated by Django 3.1.6 on 2021-04-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osoba', '__first__'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, verbose_name="Ім'я")),
                ('order_number', models.CharField(max_length=512, verbose_name='Номер наказу')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата наказу')),
                ('appruve', models.BooleanField(default=False, verbose_name='Номер наказу')),
                ('appruve_date', models.DateField(auto_now_add=True, verbose_name='appruve date')),
                ('from_staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromstaff', to='staff.staff', verbose_name='from staff')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='osoba')),
                ('to_staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tostaff', to='staff.staff', verbose_name='to staff')),
            ],
            options={
                'verbose_name': 'Переміщення',
                'verbose_name_plural': 'Переміщення',
            },
        ),
    ]
