# Generated by Django 3.1.6 on 2021-04-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0004_auto_20210430_0957'),
        ('staff', '0002_auto_20210430_0957'),
        ('relocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relocation',
            name='appruve_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата прийому на службу'),
        ),
        migrations.AlterField(
            model_name='relocation',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець'),
        ),
        migrations.AlterField(
            model_name='relocation',
            name='to_staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tostaff', to='staff.staff', verbose_name='З посади'),
        ),
    ]
