# Generated by Django 3.1.6 on 2021-06-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0003_auto_20210430_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
