# Generated by Django 3.2.6 on 2021-09-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_shpk_short_name'),
        ('relocation', '0005_auto_20210813_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статуси'},
        ),
        migrations.AlterField(
            model_name='relocation',
            name='from_staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromstaff', to='staff.staff', verbose_name='з посади'),
        ),
        migrations.AlterField(
            model_name='relocation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relocation.status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='relocation',
            name='to_staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tostaff', to='staff.staff', verbose_name='на посаду'),
        ),
    ]
