# Generated by Django 3.2.10 on 2022-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation', '0007_alter_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
    ]
