# Generated by Django 3.2.6 on 2021-08-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_adresa_kontrakt_nakaz_nakaznomer_nakazplace_name_osvitaname_peremish_phones_pidrozdilid_pidrozdilnam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='unic',
        ),
        migrations.AddField(
            model_name='staff',
            name='unicum',
            field=models.PositiveBigIntegerField(blank=True, default=3, verbose_name='Unic number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shpk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
