# Generated by Django 3.2.10 on 2022-01-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_shpk_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shpk',
            name='short_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Short name'),
        ),
    ]
