# Generated by Django 3.2.6 on 2021-09-12 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osoba', '0014_remove_serviseid_official_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, verbose_name="Ім'я")),
                ('order_number', models.CharField(max_length=512, verbose_name='Номер наказу')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата наказу')),
                ('appruve', models.BooleanField(default=False, verbose_name='Номер наказу')),
                ('appruve_date', models.DateField(auto_now_add=True, verbose_name='Дата прийому на службу')),
                ('osoba', models.ManyToManyField(to='osoba.ServiseID', verbose_name='Військовослужбовець')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.statusorder', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Переміщення',
                'verbose_name_plural': 'Переміщення',
            },
        ),
    ]
