# Generated by Django 3.2.6 on 2021-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorder',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name="Ім'я"),
        ),
    ]
