# Generated by Django 3.2.6 on 2021-09-15 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210915_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appruve_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата прийому на службу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата наказу'),
        ),
    ]
