# Generated by Django 3.2.6 on 2021-09-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210915_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Наказ', 'verbose_name_plural': 'Накази'},
        ),
        migrations.AlterModelOptions(
            name='statusorder',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статуси'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.statusorder', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='statusorder',
            name='name',
            field=models.CharField(choices=[('APP', 'Appointment'), ('MOV', 'Moving'), ('RA', 'Rank')], max_length=512, verbose_name="Ім'я"),
        ),
    ]
