# Generated by Django 3.2.6 on 2021-10-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210915_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='name',
            field=models.CharField(choices=[('APP', 'Призначення'), ('MOV', 'Переведення'), ('RA', 'Звання'), ('AL', 'Щорічна відпустка'), ('VFR', 'Відпустка по сімейним обставинам'), ('SZCH', 'Самовільне залишення частини')], max_length=512, verbose_name="Ім'я"),
        ),
    ]
