# Generated by Django 4.0 on 2021-12-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_statusorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='description',
            field=models.TextField(blank=True, verbose_name='Дата призову'),
        ),
    ]
