# Generated by Django 4.0 on 2021-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_statusorder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='name',
            field=models.CharField(choices=[('APP', 'Призначення'), ('MOV', 'Переведення'), ('RA', 'Звання'), ('AL', 'Щорічна відпустка'), ('VFR', 'Відпустка по сімейним обставинам'), ('SZCH', 'Самовільне залишення частини'), ('Reward', 'Заоохочення та нагороди'), ('Penalty', 'Догана')], max_length=512, verbose_name="Ім'я"),
        ),
    ]
