# Generated by Django 4.0 on 2021-12-31 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0017_auto_20210915_1639'),
        ('order', '0009_alter_statusorder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Дата призову')),
                ('order_number', models.CharField(max_length=512, verbose_name='Номер наказу')),
                ('date_begin', models.DateField(default=django.utils.timezone.now, verbose_name='Дата наказу')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Дата наказу')),
                ('osoba', models.ManyToManyField(to='osoba.ServiseID', verbose_name='Військовослужбовець')),
            ],
        ),
    ]
