# Generated by Django 3.2.10 on 2022-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_allcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontract',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='statusorder',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
    ]
