# Generated by Django 3.2.10 on 2022-01-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0017_auto_20210915_1639'),
        ('order', '0013_auto_20220105_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontract',
            name='order_number',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Номер наказу'),
        ),
        migrations.AlterField(
            model_name='allcontract',
            name='osoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець'),
            preserve_default=False,
        ),
    ]
