# Generated by Django 3.2.10 on 2022-01-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0018_auto_20220106_1016'),
        ('order', '0014_auto_20220105_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontract',
            name='osoba',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець'),
            preserve_default=False,
        ),
    ]
