# Generated by Django 3.1.6 on 2021-04-29 13:05

from django.db import migrations, models
import django.db.models.deletion
import osoba.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділ',
            },
        ),
        migrations.CreateModel(
            name='Creed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Віросповідання',
                'verbose_name_plural': 'Віросповідання',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
            },
        ),
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Військове звання',
                'verbose_name_plural': 'Військові звання',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Національність',
                'verbose_name_plural': 'Національності',
            },
        ),
        migrations.CreateModel(
            name='OfficialPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
                ('shpk', models.CharField(max_length=512, verbose_name='ШПК')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
            },
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роти',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Взвод',
                'verbose_name_plural': 'Взвода',
            },
        ),
        migrations.CreateModel(
            name='ServiseID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я В/С")),
                ('sename', models.CharField(max_length=512, verbose_name='Прізвище')),
                ('third_name', models.CharField(max_length=512, verbose_name='По батькові')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('image3x4', models.BinaryField(blank=True, verbose_name='image3x4')),
                ('image_face3x4', models.ImageField(blank=True, upload_to=osoba.models.image_directory_path, verbose_name='Фотокартка 3 на 4')),
                ('military_office', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Військове звання')),
                ('date_of_conscription', models.DateField(blank=True, null=True, verbose_name='Дата призову')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата наказу')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер наказу')),
                ('militaryID_seria', models.CharField(blank=True, max_length=3, null=True, verbose_name='Військовий квиток серія')),
                ('militaryID_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Військовий квиток номер')),
                ('who_militaryID', models.CharField(blank=True, max_length=10, null=True, verbose_name='Хто видав Військовий квиток')),
                ('militaryID_date', models.DateField(blank=True, null=True, verbose_name='Військовий квиток дата видачі')),
                ('weapon', models.CharField(blank=True, max_length=1020, null=True, verbose_name='Зброя')),
                ('military_rank_id', models.CharField(blank=True, max_length=1020, null=True, verbose_name='Присвоєння військового звання')),
                ('military_rank_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоєння військового звання')),
                ('ID_seria', models.CharField(blank=True, max_length=3, null=True, verbose_name='Паспорт серія')),
                ('ID_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Паспорт номер')),
                ('who_ID', models.CharField(blank=True, max_length=10, null=True, verbose_name='Хто видав Паспорт')),
                ('ID_date', models.DateField(blank=True, null=True, verbose_name='Паспорт дата видачі')),
                ('ipn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Індефікаційний код')),
                ('orphan', models.BooleanField(default=False, help_text='Сирота', verbose_name='Сирота')),
                ('married', models.BooleanField(default=False, verbose_name='Одружений')),
                ('halforphan', models.BooleanField(default=False, verbose_name='Напівсирота')),
                ('work', models.BooleanField(default=False, verbose_name='Робота')),
                ('mobilization', models.BooleanField(default=False, verbose_name='Мобілізований')),
                ('driveid', models.BooleanField(default=False, verbose_name='Посвідчення водія')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Група крові')),
                ('rh', models.CharField(blank=True, max_length=2, null=True, verbose_name='RH')),
                ('creed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.creed', verbose_name='віросповідання')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.education', verbose_name='Освіта')),
                ('military_ranks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.militaryrank', verbose_name='Військове звання')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.nationality', verbose_name='нацаональність')),
                ('official_position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.officialposition', verbose_name='Посада')),
                ('platoon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.platoon', verbose_name='Рота')),
                ('unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.unit', verbose_name='Взвод')),
            ],
            options={
                'verbose_name': 'Військовослужбовець',
                'verbose_name_plural': 'Військовослужбовці',
            },
        ),
    ]
