# Generated by Django 3.1.6 on 2021-02-22 16:23

from django.db import migrations, models
import django.db.models.deletion
import osoba.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Військове звання',
                'verbose_name_plural': 'Військові звання',
            },
        ),
        migrations.CreateModel(
            name='OfficialPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
                ('shpk', models.CharField(max_length=512, verbose_name='ШПК')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
            },
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роти',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Взвод',
                'verbose_name_plural': 'Взвода',
            },
        ),
        migrations.CreateModel(
            name='ServiseID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я В/С")),
                ('sename', models.CharField(max_length=512, verbose_name='Прізвище')),
                ('third_name', models.CharField(max_length=512, verbose_name='По батькові')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('image3x4', models.BinaryField(blank=True, verbose_name='image3x4')),
                ('image_face3x4', models.ImageField(blank=True, upload_to=osoba.models.image_directory_path, verbose_name='Фотокартка 3 на 4')),
                ('military_office', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Military office')),
                ('date_of_conscription', models.DateField(auto_now_add=True, null=True, verbose_name='date of conscription')),
                ('order_date', models.DateField(auto_now_add=True, null=True, verbose_name='order date')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='order number')),
                ('military_ranks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.militaryrank', verbose_name='Військове звання')),
                ('official_position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.officialposition', verbose_name='Посада')),
                ('platoon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.platoon', verbose_name='Взвод')),
                ('unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.unit', verbose_name='Рота')),
            ],
            options={
                'verbose_name': 'Військовослужбовець',
                'verbose_name_plural': 'Військовослужбовці',
            },
        ),
    ]
