# Generated by Django 3.1.6 on 2021-02-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryRanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ServiseID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('sename', models.CharField(max_length=512)),
                ('third_name', models.CharField(max_length=512)),
                ('birth_date', models.DateField()),
                ('military_ranks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.militaryranks')),
                ('platoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.platoon')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.unit')),
            ],
        ),
    ]
