# Generated by Django 3.1.6 on 2021-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviseid',
            name='date_of_conscription',
            field=models.DateField(blank=True, null=True, verbose_name='date of conscription'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='order date'),
        ),
    ]
