# Generated by Django 3.1.6 on 2021-02-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MilitaryRanks',
            new_name='MilitaryRank',
        ),
    ]
