# Generated by Django 3.1.6 on 2021-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0002_auto_20210211_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='image3x4',
            field=models.BinaryField(blank=True),
        ),
    ]
