# Generated by Django 3.1.6 on 2021-04-29 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0002_auto_20210429_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviseid',
            name='platoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.platoon', verbose_name='Рота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.unit', verbose_name='Взвод'),
        ),
    ]
