# Generated by Django 3.1.6 on 2021-02-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0002_auto_20210222_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Підрозділ', 'verbose_name_plural': 'Підрозділ'},
        ),
        migrations.AddField(
            model_name='serviseid',
            name='ipn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ipn'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='militaryID_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='militaryID number'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='militaryID_seria',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='militaryID seria'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='orphan',
            field=models.BooleanField(default=False, help_text='orphan', verbose_name='orphan'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='date_of_conscription',
            field=models.DateField(blank=True, null=True, verbose_name='Дата призову'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_office',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Військове звання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер наказу'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='platoon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.platoon', verbose_name='Рота'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.unit', verbose_name='Взвод'),
        ),
    ]
