# Generated by Django 3.1.6 on 2021-02-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0003_auto_20210222_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Creed',
                'verbose_name_plural': 'Creed',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
            },
        ),
        migrations.AddField(
            model_name='serviseid',
            name='driveid',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='driveid'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='halforphan',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='halforphan'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='married',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='married'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='mobilization',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='mobilization'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='weapon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Індефікаційний код'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='work',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='ipn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Індефікаційний код'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='militaryID_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Військовий квиток номер'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='militaryID_seria',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Військовий квиток серія'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='orphan',
            field=models.BooleanField(default=False, help_text='Сирота', verbose_name='Сирота'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='creed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.creed', verbose_name='creed'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.education', verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.nationality', verbose_name='nationality'),
        ),
    ]
