# Generated by Django 3.1.6 on 2021-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0004_auto_20210222_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviseid',
            name='driveid',
            field=models.BooleanField(default=False, verbose_name='driveid'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='halforphan',
            field=models.BooleanField(default=False, verbose_name='halforphan'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='married',
            field=models.BooleanField(default=False, verbose_name='married'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='mobilization',
            field=models.BooleanField(default=False, verbose_name='mobilization'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='weapon',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='weapon'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='work',
            field=models.BooleanField(default=False, verbose_name='work'),
        ),
    ]
