# Generated by Django 3.1.6 on 2021-02-16 07:48

from django.db import migrations, models
import django.db.models.deletion
import osoba.models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0004_serviseid_image_face3x4'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('shpk', models.CharField(max_length=512, verbose_name='SHPK')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
            },
        ),
        migrations.AlterModelOptions(
            name='militaryrank',
            options={'verbose_name': 'Військове звання', 'verbose_name_plural': 'Військові звання'},
        ),
        migrations.AlterModelOptions(
            name='platoon',
            options={'verbose_name': 'Рота', 'verbose_name_plural': 'Роти'},
        ),
        migrations.AlterModelOptions(
            name='serviseid',
            options={'verbose_name': 'Військовослужбовець', 'verbose_name_plural': 'Військовослужбовці'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Взвод', 'verbose_name_plural': 'Взвода'},
        ),
        migrations.AlterField(
            model_name='militaryrank',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='birth_date',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='image_face3x4',
            field=models.ImageField(blank=True, upload_to=osoba.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='name',
            field=models.CharField(max_length=512, verbose_name="Ім'я В/С"),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='sename',
            field=models.CharField(max_length=512, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='third_name',
            field=models.CharField(max_length=512, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='official_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='osoba.officialposition'),
            preserve_default=False,
        ),
    ]
