# Generated by Django 3.1.6 on 2021-02-18 09:52

from django.db import migrations, models
import django.db.models.deletion
import osoba.models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0005_auto_20210216_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='image3x4',
            field=models.BinaryField(blank=True, verbose_name='image3x4'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='image_face3x4',
            field=models.ImageField(blank=True, upload_to=osoba.models.image_directory_path, verbose_name='image_face3x4'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_ranks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osoba.militaryrank', verbose_name='military rank'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='official_position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.officialposition', verbose_name='official_position'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='platoon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.platoon', verbose_name='platoon'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.unit', verbose_name='unit'),
        ),
    ]
