# Generated by Django 3.1.6 on 2021-02-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0005_auto_20210222_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='blood_type'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='rh',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='RH'),
        ),
    ]
