# Generated by Django 3.1.6 on 2021-02-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0006_auto_20210223_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creed',
            options={'verbose_name': 'Віросповідання', 'verbose_name_plural': 'Віросповідання'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Освіта', 'verbose_name_plural': 'Освіта'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Національність', 'verbose_name_plural': 'Ноціональності'},
        ),
        migrations.AddField(
            model_name='serviseid',
            name='militaryID_date',
            field=models.DateField(blank=True, null=True, verbose_name='militaryID_date'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='who_militaryID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='who_militaryID'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Група крові'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='creed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.creed', verbose_name='віросповідання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='driveid',
            field=models.BooleanField(default=False, verbose_name='Посвідчення водія'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.education', verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='halforphan',
            field=models.BooleanField(default=False, verbose_name='Напівсирота'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='married',
            field=models.BooleanField(default=False, verbose_name='Одружений'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.nationality', verbose_name='нацаональність'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='weapon',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='Зброя'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='work',
            field=models.BooleanField(default=False, verbose_name='Робота'),
        ),
    ]
