# Generated by Django 3.1.6 on 2021-06-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0006_auto_20210604_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='name_accs',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Name Person in accs'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='sename_accs',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Sename in accs'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='third_name_accs',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='third name  in accs'),
        ),
    ]
