# Generated by Django 3.1.6 on 2021-02-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0007_auto_20210223_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='ID_date',
            field=models.DateField(blank=True, null=True, verbose_name='ID_date'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='ID_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='ID_seria',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ID seria'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='who_ID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='who_ID'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='militaryID_date',
            field=models.DateField(blank=True, null=True, verbose_name='Військовий квиток дата видачі'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='mobilization',
            field=models.BooleanField(default=False, verbose_name='Мобілізований'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='who_militaryID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Хто видав Військовий квиток'),
        ),
    ]
