# Generated by Django 3.1.6 on 2021-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0009_auto_20210223_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Національність', 'verbose_name_plural': 'Національності'},
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_rank_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присвоєння військового звання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='military_rank_id',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='Присвоєння військового звання'),
        ),
    ]
