# Generated by Django 3.2.6 on 2021-08-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0011_militaryrank_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviseid',
            name='platoon',
        ),
        migrations.RemoveField(
            model_name='serviseid',
            name='unit',
        ),
    ]
