# Generated by Django 3.2.6 on 2021-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0012_auto_20210819_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(default=2, max_length=512, verbose_name='Short name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='unik',
            field=models.PositiveBigIntegerField(blank=True, default=2, verbose_name='Unic number'),
            preserve_default=False,
        ),
    ]
