# Generated by Django 3.2.6 on 2021-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0016_alter_command_temporarily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Командування', 'verbose_name_plural': 'Командування'},
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(choices=[('KB', 'Командир батальйону'), ('ZKB', 'Замісник командира батальйону'), ('ZKBMPZ', 'Замісник командира батальйону з морально-психологічної роботи'), ('PKBZPR', 'Помічник командира батальйону з юридичних питань'), ('OP', 'Офіцер-психолог'), ('GSVCH', 'Головний сержант батальйону'), ('Tehnic', 'Технік'), ('ZKBPDP', 'Заступник командира батальйону з повітряно-десантної підготовки'), ('ZKBNSH', 'Начальник штабу - перший заступник командира батальйону'), ('SPZKISCH', 'Старший помічник начальника штабу з кадрів і стройової частини')], max_length=512, verbose_name='Name Command'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='addres_fact',
            field=models.TextField(blank=True, null=True, verbose_name='адреса фактичного проживання'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='addres_pr',
            field=models.TextField(blank=True, null=True, verbose_name='адреса прописки'),
        ),
    ]
