# Generated by Django 3.2.10 on 2022-01-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0017_auto_20210915_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone home'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone mobile'),
        ),
    ]
