# Generated by Django 3.2.10 on 2022-01-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0018_auto_20220106_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='serviseid',
            name='postal_code_fact',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone home'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='postal_code_pr',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone home'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='region_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osoba.region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='region_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osoba.region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='state_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osoba.state', verbose_name='state'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='state_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osoba.state', verbose_name='state'),
        ),
    ]
