# Generated by Django 3.2.10 on 2022-01-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0019_auto_20220106_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='father',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='phone home'),
        ),
        migrations.AddField(
            model_name='serviseid',
            name='mother',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='phone mobile'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='addres_fact',
            field=models.TextField(blank=True, null=True, verbose_name='address fact'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='postal_code_fact',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='postal_code_pr',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='postal code_pr'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='region_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osoba.region', verbose_name='region fact'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='state_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osoba.state', verbose_name='state fact'),
        ),
    ]
