# Generated by Django 3.2.10 on 2022-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0020_auto_20220106_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='partner',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='father',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='father'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='mother',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='mother'),
        ),
    ]
