# Generated by Django 3.2.10 on 2022-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0022_auto_20220111_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryrank',
            name='short_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Short name'),
        ),
    ]
