# Generated by Django 4.0 on 2022-02-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0023_alter_militaryrank_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviseid',
            name='nickname',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='serviseid',
            name='third_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='По батькові'),
        ),
    ]
