# Generated by Django 3.1.6 on 2021-04-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osoba', '0004_auto_20210430_0957'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='vacant',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Вакантна'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ocoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osoba.serviseid', verbose_name='Військовослужбовець'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='poz',
            field=models.CharField(blank=True, max_length=512, verbose_name='Позивний'),
        ),
    ]
