# Generated by Django 3.2.6 on 2021-08-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210813_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='unic',
            new_name='unicum',
        ),
    ]
