# Generated by Django 3.2.6 on 2021-08-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210816_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='unicum',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Unic number'),
        ),
    ]
